export type LocaleText={zh:string;en:string}
export type BridgeMethod={name:string;signature:string;description:LocaleText;usageCode:string}
export const importCode="import Bridge from './Bridge';"
export const methods:BridgeMethod[]=[
{name:'routeTo',signature:'routeTo(path, params?)',description:{zh:'**跳转到 App 指定页面。** `params` 支持字符串或对象，并兼容新旧版本路由协议。',en:'**Navigate to a page in the app.** `params` accepts a string or object and supports modern and legacy routing.'},usageCode:"Bridge.routeTo('/trade/spot', { symbol: 'BTC_USDT' });"},
{name:'share',signature:'share(imageBase64)',description:{zh:'**分享一张图片。** 传入 Base64 图片数据，由原生 App 拉起分享。',en:'**Share an image.** Pass Base64 image data and let the native app open its sharing interface.'},usageCode:'Bridge.share(imageBase64);'},
{name:'getToken',signature:'getToken()',description:{zh:'**获取当前用户令牌。** 原生方法不可用或调用失败时返回空字符串。',en:'**Get the current user token.** Returns an empty string when the native method is unavailable or fails.'},usageCode:'const token = Bridge.getToken();'},
{name:'getVersion',signature:'getVersion()',description:{zh:'**获取 JS Bridge 协议版本。** 可用于判断当前 App 支持的通信能力。',en:'**Get the JS Bridge protocol version.** Useful for checking supported communication capabilities.'},usageCode:'const bridgeVersion = Bridge.getVersion();'},
{name:'getAppVersion',signature:'getAppVersion()',description:{zh:'**获取 App 版本号。** 调用原生 `appVersion` 方法并返回结果。',en:'**Get the app version.** Calls the native `appVersion` method and returns its result.'},usageCode:'const appVersion = Bridge.getAppVersion();'},
{name:'hasNativeMethod',signature:'hasNativeMethod(action)',description:{zh:'**检查原生方法是否存在。** 适合调用前进行能力检测，异常时返回 `false`。',en:'**Check whether a native method exists.** Use it for capability detection before invoking a method.'},usageCode:"const canShare = Bridge.hasNativeMethod('share');"},
{name:'call',signature:'call(action, data, callback?)',description:{zh:'**调用任意原生方法。** 支持动作名、数据和可选回调，是通用 Bridge 入口。',en:'**Invoke any native method.** Accepts an action, data and optional callback.'},usageCode:"Bridge.call('customAction', { value: 1 }, (result) => {\n  console.log(result);\n});"},
{name:'getAppTheme',signature:'getAppTheme()',description:{zh:'**获取 App 当前主题。** 可让 H5 页面与原生浅色或深色主题保持同步。',en:'**Get the current app theme.** Synchronize the web page with the native light or dark theme.'},usageCode:'const theme = Bridge.getAppTheme();'},
{name:'getAppLang',signature:'getAppLang()',description:{zh:'**获取 App 当前语言。** 可作为 H5 国际化语言初始化依据。',en:'**Get the current app language.** It can initialize the locale used by the web experience.'},usageCode:'const language = Bridge.getAppLang();'}]
